# Generated by Django 4.1 on 2022-09-03 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="slug",
            field=models.SlugField(
                allow_unicode=True,
                blank=True,
                max_length=225,
                null=True,
                unique=True,
                verbose_name="Slug",
            ),
        ),
    ]
